version: "2"
checks:
  method-complexity:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
  identical-code:
    config:
      threshold: 1
plugins:
  duplication:
    enabled: true
    count_threshold: 1
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc